import { useEffect, useState } from 'react'
import { LineChart, Line, AreaChart, Area, BarChart, Bar, Cell, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, ReferenceLine, LabelList } from 'recharts'
import { Activity, ArrowDownRight, ArrowRight, Check, CheckCircle2, Clock3, Download, Info, ShieldCheck, TriangleAlert, TrendingUp, Zap, Play, Pause, SkipBack, ChevronLeft, ChevronRight } from 'lucide-react'
import { availability, number, inr, type Result, type Run } from './types'
import { exportRun } from './exports'
import { FacilityDiagram } from './Visualizer'
const COLORS = ['#8191aa', '#ec7848', '#23947d']
const tipStyle = {background:'#fff',border:'1px solid #e5e8ef',borderRadius:9,fontSize:12,boxShadow:'0 6px 24px #17233212'}
export function Metrics({result}: {result: Result}) {
  return <div className="metrics-grid">
    <div className="metric panel"><div className="metric-label">Estimated availability<ShieldCheck size={16}/></div><strong>{availability(result.availability_percent)}<span>%</span></strong><div className={result.meets_sla?'metric-note good':'metric-note bad'}>{result.meets_sla?<TrendingUp size={13}/>:<TriangleAlert size={13}/>} {result.meets_sla?'Above':'Below'} SLA benchmark</div></div>
    <div className="metric panel"><div className="metric-label">Annual downtime<Clock3 size={16}/></div><strong>{number(result.expected_annual_downtime_minutes,2)}<span>min</span></strong><div className="metric-note">Expected per simulated year</div></div>
    <div className="metric panel"><div className="metric-label">SLA breach rate<Activity size={16}/></div><strong>{number(result.sla_breach_rate_percent,2)}<span>%</span></strong><div className="metric-note">{number(result.sla_breaches)} of {number(result.trials_run)} trials</div></div>
    <div className="metric panel"><div className="metric-label">Planning budget<Zap size={16}/></div><strong>{result.budget?`${number(result.budget.total_inr/10000000,2)}`:number(result.infra_cost_index,2)}<span>{result.budget?'₹ Cr':'×'}</span></strong><div className="metric-note">{result.budget?'Editable assumptions · not quotes':'Legacy unit-count index'}</div></div>
  </div>
}
export function ResultsDashboard({run, onCompare}: {run: Run; onCompare: ()=>void}) {
  const [tab,setTab] = useState('overview')
  const r = run.results[0]
  const [eventFilter,setEventFilter] = useState('all')
  const lower = Math.min(r.sla_target_percent,...r.convergence.map(x=>x.availability))
  const domain = [Math.max(0,Math.floor((lower-.0005)*1000)/1000),100]
  const events = r.sample_events.filter(e=>eventFilter==='all'||!e.service_maintained)
  return <>
    <div className="results-heading"><div><h3>Simulation results</h3><span className="badge success"><Check size={11}/>Completed</span></div><span className="subtle">{number(r.trials_run)} trials · {run.duration_seconds.toFixed(2)}s runtime</span></div>
    <Metrics result={r}/>
    <EvidencePanel result={r} years={run.config.simulation.simulated_years_per_trial}/>
    <ScenarioSummary run={run} result={r}/>
    <div className="results-tabs"><div role="tablist" aria-label="Simulation result views" onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]'));const current=tabs.indexOf(document.activeElement as HTMLButtonElement);const index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(current+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[index].focus();tabs[index].click()}}>{[['overview','Overview'],['distribution','Trial distribution'],['events','Event samples'],['replay','Trial replay']].map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><button className="text-button" onClick={()=>exportRun(run,'trials')}><Download size={13}/>Trial data</button></div>
    {tab==='overview' && <div className="charts-grid"><section className="panel convergence-panel"><div className="chart-heading"><div><h3>Availability convergence</h3><p>Cumulative estimate across simulation trials</p></div><span className="small-tag">{r.redundancy}</span></div><div className="chart-legend"><span><i style={{background:'#ea7849'}}/>Estimated availability</span><span><i className="dashed"/>SLA benchmark</span></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><AreaChart data={r.convergence} margin={{top:10,right:16,left:0,bottom:5}}><defs><linearGradient id="convergence-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ef8055" stopOpacity={.18}/><stop offset="100%" stopColor="#ef8055" stopOpacity={.01}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#edf0f3"/><XAxis dataKey="trials" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8c94a2'}} tickFormatter={v=>v>=1000?`${v/1000}k`:v} minTickGap={25}/><YAxis domain={domain} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8c94a2'}} tickFormatter={v=>`${v.toFixed(3)}%`} width={76} tickCount={4}/><Tooltip contentStyle={tipStyle} formatter={v=>[`${Number(v).toFixed(6)}%`,'Availability']} labelFormatter={v=>`${number(Number(v))} trials`}/><ReferenceLine y={r.sla_target_percent} stroke="#a2adba" strokeDasharray="5 4"/><Area isAnimationActive={false} type="monotone" dataKey="availability" stroke="#ed794b" strokeWidth={2} fill="url(#convergence-fill)"/></AreaChart></ResponsiveContainer></div><div className="chart-footer">{r.availability_ci_method==='conservative-outage-risk-bound'?'Conservative 95% bound':'Approx. 95% mean CI'} <span>{r.availability_ci95.map(x=>x.toFixed(5)).join(' – ')}%</span></div></section>
    <section className="panel breakdown-panel"><div className="chart-heading"><div><h3>Failure breakdown</h3><p>Operating failure events · not a sensitivity ranking</p></div><span className="icon-muted"><Activity size={16}/></span></div><div className="breakdown-list">{[...r.failure_breakdown].sort((a,b)=>b.failures-a.failures).map((b,i)=><div key={b.kind}><div><span><i style={{background:['#ed7848','#7a91b7','#a7b7cc','#60aa9b','#b4bccc'][i%5]}}/>{b.component}</span><strong>{number(b.failures)}</strong></div><div className="breakdown-track"><i style={{width:`${Math.max(0,b.failures/Math.max(1,r.total_failure_events)*100)}%`,background:['#ed7848','#7a91b7','#a7b7cc','#60aa9b','#b4bccc'][i%5]}}/></div></div>)}</div><div className="breakdown-total"><span>Total injected events</span><strong>{number(r.total_failure_events)}</strong></div></section></div>}
    {tab==='distribution' && <section className="panel"><div className="chart-heading"><div><h3>Annualized downtime distribution</h3><p>How often did the facility experience an interruption?</p></div><span className="small-tag">{number(r.outage_trials)} outage trials</span></div><div className="distribution-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={r.histogram} margin={{top:25,right:25,bottom:10,left:10}}><CartesianGrid vertical={false} strokeDasharray="3 4"/><XAxis dataKey="range" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tipStyle}/><Bar dataKey="trials" fill="#ec7848" radius={[5,5,0,0]} maxBarSize={70}>{r.histogram.map((_,i)=><Cell key={i} fill={i===0?'#38a38b':'#ed8055'}/>)}<LabelList dataKey="trials" position="top" style={{fontSize:11,fill:'#657081'}}/></Bar></BarChart></ResponsiveContainer></div><div className="chart-footer">95th percentile annual downtime <span>{number(r.p95_annual_downtime_minutes,2)} min</span></div></section>}
    {tab==='overview'&&<section className="panel diagnostic-panel"><div className="chart-heading"><div><h3>Convergence checkpoints</h3><p>Sample uncertainty as trial count grows. Sparse events can still give unstable estimates.</p></div></div><div className="table-scroll"><table><thead><tr><th>Trials</th><th>Availability</th><th>95% mean interval / zero-outage bound</th><th>Outage trials</th></tr></thead><tbody>{r.convergence.filter((_,i)=>i%10===9).map(p=><tr key={p.trials}><td>{number(p.trials)}</td><td>{availability(p.availability)}%</td><td>{p.ci_low!==undefined?`${p.ci_low.toFixed(6)} – ${p.ci_high?.toFixed(6)}%`:'Legacy run: rerun for intervals'}</td><td>{p.outage_trials??'—'}</td></tr>)}</tbody></table></div></section>}
    {tab==='replay' && <TrialReplay run={run} result={r}/>}
    {tab==='events' && <section className="panel"><div className="chart-heading"><div><h3>Failure event samples</h3><p>First 60 events, ordered by trial—not a representative event sample.</p></div><select aria-label="Filter failure events" className="compact-select" value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option value="all">All events</option><option value="impact">Service interrupted</option></select></div><div className="table-scroll events-table"><table><thead><tr><th>Trial</th><th>Component / cause</th><th>At hour</th><th>Repair time</th><th>Capacity</th><th>Service</th></tr></thead><tbody>{events.map((e,i)=><tr key={i}><td className="mono">#{e.trial_id}</td><td className="mono">{e.component}<small className="table-sub">{e.kind}</small></td><td>{number(e.time_hours,2)}</td><td>{e.duration_hours} h</td><td>{number(e.surviving_capacity_kw)} kW</td><td><span className={`badge ${e.service_maintained?'success':'danger'}`}>{e.service_maintained?'Maintained':'Interrupted'}</span></td></tr>)}</tbody></table>{!events.length&&<div className="empty-inline">No interruptions in the captured event samples. Full aggregate results are shown above.</div>}</div></section>}
    <DiagnosticResults run={run}/>
    <div className="result-insight"><div className="insight-icon"><ShieldCheck size={20}/></div><div><strong>{r.meets_sla?'Your design meets the selected mean-availability benchmark.':'This design falls below the selected availability benchmark.'}</strong><p>{number(r.overlap_trials)} trials contained overlapping failures. {r.outage_trials===0?`No outages observed; 95% upper bound on trial outage probability is ${(r.outage_probability_ci95[1]*100).toFixed(3)}%.`:`${number(r.outage_trials)} trials lost IT service; uptime is not guaranteed by the mean.`}</p></div><button onClick={onCompare}>Compare designs<ArrowRight size={15}/></button></div>
    <div className="inline-note"><Info size={14}/><span>Mixed-source research demo · {run.config.simulation.operating_mode} scenario · {run.config.simulation.stress_multiplier}× hazard rate. Estimates are model-dependent, not Tier certification.</span></div>
  </>
}
export function Comparison({run}: {run: Run}) {
  const rs = run.results
  const min = Math.min(...rs.map(r=>r.availability_percent))
  const nDown = rs[0].expected_annual_downtime_minutes
  const best = [...rs].filter(r=>r.meets_sla).sort((a,b)=>a.infra_cost_index-b.infra_cost_index)[0]
  return <div className="comparison-results"><div className="comparison-summary"><div><span className="eyebrow">CONTROLLED COMPARATIVE STUDY</span><h2>Same load. Different resilience.</h2><p>{number(run.config.it_load_kw)} kW · {number(run.config.simulation.num_trials)} trials per design · seed {run.config.simulation.seed}</p></div><span className="badge success"><CheckCircle2 size={13}/>Experiment complete</span></div>
    <div className="architecture-cards">{rs.map((r,i)=><article className={`panel architecture-card ${r.redundancy===best?.redundancy?'recommended':''}`} key={r.redundancy}><div className="architecture-top"><span className="architecture-symbol" style={{color:COLORS[i],background:`${COLORS[i]}13`}}>{r.redundancy}</span>{r.redundancy===best?.redundancy?<span className="badge orange">Lowest count · observed fit</span>:<span className="subtle">{['Baseline','One spare / group','Independent A/B paths'][i]}</span>}</div><strong>{availability(r.availability_percent)}<small>%</small></strong><span className="subtle">Estimated availability</span><div className="architecture-stats"><div><span>Annual downtime</span><b>{number(r.expected_annual_downtime_minutes,2)} min</b></div><div><span>Planning budget (not a quote)</span><b>{r.budget?inr(r.budget.total_inr):`${number(r.infra_cost_index,2)}×`}</b></div><div><span>Installed components</span><b>{r.component_count}</b></div></div><div className={`architecture-status ${r.meets_sla?'good':'bad'}`}>{r.meets_sla?<CheckCircle2 size={14}/>:<TriangleAlert size={14}/>} {r.meets_sla?'Meets mean SLA benchmark':'Below mean SLA benchmark'}</div></article>)}</div>
    {rs.map(r=><ScenarioSummary key={r.redundancy} run={run} result={r}/>)}
    <div className="charts-grid equal"><section className="panel"><div className="chart-heading"><div><h3>Availability by architecture</h3><p>Percent uptime · zoomed vertical axis</p></div></div><div className="comparison-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rs} margin={{left:10,right:20,top:25,bottom:5}}><CartesianGrid vertical={false} strokeDasharray="3 4" stroke="#e9edf2"/><XAxis dataKey="redundancy" tickLine={false} axisLine={false} tick={{fontSize:12}}/><YAxis domain={[Math.max(0,Math.floor((min-.01)*100)/100),100]} tickFormatter={v=>`${v.toFixed(2)}%`} tick={{fontSize:10}} width={65} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[`${Number(v).toFixed(6)}%`,'Availability']} contentStyle={tipStyle}/><ReferenceLine y={rs[0].sla_target_percent} stroke="#8892a1" strokeDasharray="4 4"/><Bar dataKey="availability_percent" radius={[5,5,0,0]} maxBarSize={65}>{rs.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Bar></BarChart></ResponsiveContainer></div></section><section className="panel"><div className="chart-heading"><div><h3>The downtime trade-off</h3><p>Expected minutes of downtime per year</p></div></div><div className="comparison-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rs} margin={{left:10,right:30,top:25,bottom:5}}><CartesianGrid vertical={false} strokeDasharray="3 4" stroke="#e9edf2"/><XAxis dataKey="redundancy" tickLine={false} axisLine={false} tick={{fontSize:12}}/><YAxis tick={{fontSize:10}} width={45} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[`${number(Number(v),3)} min`,'Annual downtime']} contentStyle={tipStyle}/><Bar dataKey="expected_annual_downtime_minutes" radius={[5,5,0,0]} maxBarSize={65}>{rs.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Bar></BarChart></ResponsiveContainer></div></section></div>
    <section className="panel"><div className="chart-heading"><div><h3>Experiment results</h3><p>Identical load, component ratings, horizon, and hazard assumptions.</p></div><button className="text-button" onClick={()=>exportRun(run,'csv')}><Download size={14}/>Export CSV</button></div><div className="table-scroll"><table><thead><tr><th>Architecture</th><th>Availability (95% interval)</th><th>Downtime / year</th><th>SLA breaches</th><th>Cost index</th><th>Overlapping trials</th></tr></thead><tbody>{rs.map(r=><tr key={r.redundancy}><td><b>{r.redundancy}</b></td><td>{availability(r.availability_percent)}%<small className="table-sub">{r.availability_ci95.map(x=>x.toFixed(5)).join(' – ')}%</small><small className="table-sub">{r.availability_ci_method==='conservative-outage-risk-bound'?'Conservative bound':'Approximate mean CI'} · {r.outage_trials<30?'limited outage evidence':'sample-based'}</small></td><td>{number(r.expected_annual_downtime_minutes,3)} min</td><td>{number(r.sla_breach_rate_percent,2)}%<small className="table-sub">{number(r.sla_breaches)} trials</small></td><td>{number(r.infra_cost_index,2)}×</td><td>{number(r.overlap_trials)}</td></tr>)}</tbody></table></div></section>
    {!!run.paired_comparisons?.length&&<section className="panel paired-panel"><div className="chart-heading"><div><h3>Is the difference supported by the sample?</h3><p>Paired trial differences using shared component streams. Positive values mean less downtime.</p></div></div><div className="table-scroll"><table><thead><tr><th>Change in design</th><th>Minutes saved / year</th><th>Approx. paired 95% CI</th><th>Interpretation</th></tr></thead><tbody>{run.paired_comparisons.map(p=><tr key={`${p.baseline}-${p.alternative}`}><td><b>{p.baseline} → {p.alternative}</b></td><td>{number(p.downtime_reduction_minutes,3)}</td><td>{p.ci95.map(v=>number(v,3)).join(' to ')}</td><td>{p.evidence_limited?'Too few differing trials':p.ci95[0]>0?'Reduction supported':p.ci95[1]<0?'Increase supported':'Difference unresolved'}</td></tr>)}</tbody></table></div><div className="inline-note"><Info size={14}/><span>Normal intervals are approximate and do not capture uncertain input rates or omitted failure mechanisms. A point estimate is not a procurement recommendation.</span></div></section>}
    <DiagnosticResults run={run}/>
    <div className="result-insight"><div className="insight-icon"><ArrowDownRight size={21}/></div><div><strong>{best?`${best.redundancy} is the lowest unit-count design meeting the mean SLA benchmark in this run.`:'None of the tested designs meets the mean SLA benchmark.'}</strong><p>{nDown>0?`N+1 changes expected downtime by ${number((1-rs[1].expected_annual_downtime_minutes/nDown)*100,2)}% relative to N. `:''}The count index uses equal weights; INR budgets are editable assumptions, not vendor quotes. Rare-event rankings can vary by seed.</p></div></div><div className="inline-note"><Info size={15}/><span>Zero observed downtime is not infinite reliability. This {run.config.simulation.stress_multiplier}× {run.config.simulation.operating_mode} experiment uses illustrative PDU/cooling/IT values. Download JSON for complete assumptions and data provenance.</span></div>
  </div>
}


function EvidencePanel({result:r, years}: {result:Result; years:number}) {
  const sparse=r.outage_trials<30
  const status=r.evidence_status
  return <section className={`evidence-panel ${sparse?'limited':''}`} aria-label="Statistical evidence">
    <div className="evidence-heading"><span>{sparse?<TriangleAlert size={17}/>:<ShieldCheck size={17}/>}<strong>{sparse?'Limited outage evidence':status==='above'?'Mean interval above benchmark':status==='below'?'Mean interval below benchmark':'Benchmark evidence is inconclusive'}</strong></span><span className="small-tag">{number(r.outage_trials)} outage trials</span></div>
    <p>{sparse?'Fewer than 30 outage trials is a caution flag, not a formal adequacy test. More trials may be needed; zero observed outages never proves perfect reliability.':'The interval measures sampling uncertainty under this model, not uncertainty in failure-rate data or real-world Tier compliance.'}</p>
    <div className="evidence-stats"><div><span>Annual SLA downtime budget</span><b>{number(r.annual_sla_budget_minutes??(1-r.sla_target_percent/100)*525600,3)} min</b></div><div><span>Any outage · exact 95% risk interval</span><b>{r.outage_probability_ci95.map(v=>number(v*100,3)).join('–')}%</b></div><div><span>SLA breach · exact 95% risk interval</span><b>{r.sla_breach_probability_ci95?.map(v=>number(v*100,3)).join('–')??'Rerun for interval'}{r.sla_breach_probability_ci95?'%':''}</b></div><div><span>Expected unserved energy / year</span><b>{number(r.expected_unserved_energy_kwh_per_year,2)} kWh</b></div></div>
    <small>Risk probabilities refer to a complete {years}-year trial. SLA breaches use the full-horizon average, not a separate check of each year.</small>
  </section>
}

function TrialReplay({run,result:r}: {run:Run;result:Result}) {
  const [index,setIndex]=useState(0)
  const [playing,setPlaying]=useState(false)
  const trace=r.worst_trial?.timeline??[]
  useEffect(()=>{
    if(!playing)return
    if(index>=trace.length-1){setPlaying(false);return}
    const timer=setTimeout(()=>setIndex(i=>i+1),850)
    return()=>clearTimeout(timer)
  },[playing,index,trace.length])
  if(!r.worst_trial)return <div className="panel empty-inline">This saved run predates trial replay. Run the experiment again to capture a timeline.</div>
  const point=trace[Math.min(index,trace.length-1)]
  const firstOutage=trace.findIndex(p=>!p.service_maintained)
  const select=(i:number)=>{setPlaying(false);setIndex(i)}
  const state={groups:r.topology,surviving_capacity_kw:point.surviving_capacity_kw,power_capacity_kw:point.power_capacity_kw,cooling_capacity_kw:point.cooling_capacity_kw,it_capacity_kw:point.it_capacity_kw,required_capacity_kw:run.config.it_load_kw,lost_capacity_kw:Math.max(0,run.config.it_load_kw-point.surviving_capacity_kw),service_maintained:point.service_maintained,failed_components:point.failed_components}
  return <section className="replay-section">
    <div className="panel replay-panel"><div className="chart-heading"><div><h3>Inside an actual simulated trial</h3><p>Trial #{r.worst_trial.trial_id} · highest observed downtime, not a typical year</p></div><span className="small-tag">{number(r.worst_trial.downtime_minutes,2)} min lost over {run.config.simulation.simulated_years_per_trial} year(s)</span></div>
      <div className="replay-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trace} margin={{left:10,right:25,top:15,bottom:10}}><CartesianGrid vertical={false} strokeDasharray="3 4"/><XAxis dataKey="time_hours" type="number" domain={[0,r.worst_trial.horizon_hours]} tick={{fontSize:10}} tickFormatter={v=>`${number(v)} h`}/><YAxis domain={[0,run.config.it_load_kw*1.05]} tick={{fontSize:10}} width={64} tickFormatter={v=>`${number(v/1000,1)} MW`}/><Tooltip contentStyle={tipStyle} labelFormatter={v=>`Hour ${number(Number(v),3)}`} formatter={v=>[`${number(Number(v))} kW`,'Served IT load']}/><ReferenceLine y={run.config.it_load_kw} stroke="#8996a8" strokeDasharray="4 3"/><ReferenceLine x={point.time_hours} stroke="#ed7848" strokeWidth={2}/><Line type="stepAfter" dataKey="served_it_kw" stroke="#23947d" dot={false} strokeWidth={2} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>
      <div className="replay-controls"><button className="button" aria-label="Restart trial replay" onClick={()=>select(0)}><SkipBack size={15}/></button><button className="button" aria-label="Previous replay event" disabled={index===0} onClick={()=>select(index-1)}><ChevronLeft size={15}/></button><button className="button primary" onClick={()=>{if(index===trace.length-1)setIndex(0);setPlaying(!playing)}}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'Pause':'Play'} replay</button><button className="button" aria-label="Next replay event" disabled={index===trace.length-1} onClick={()=>select(index+1)}><ChevronRight size={15}/></button><button className="button" disabled={firstOutage<0} onClick={()=>select(firstOutage)}>Jump to first outage</button><span>Event {index+1} / {trace.length} · event-time playback</span></div>
      <div className="replay-scrubber"><input aria-label="Replay event position" type="range" min={0} max={trace.length-1} step={1} value={index} onChange={e=>select(Number(e.target.value))}/></div>
      <div className={`replay-event ${point.service_maintained?'':'interrupted'}`} aria-live="polite"><span className="mono">HOUR {number(point.time_hours,3)}</span><strong>{point.action==='start'?'All equipment healthy':point.action==='end'?'End of trial':`${point.component} ${point.action==='repair'?'cause cleared':'cause started'}`}</strong><span>{point.failed_components.length} active failures · {point.service_maintained?'Service protected':'Service interrupted'}</span></div>
    </div>
    <FacilityDiagram state={state} config={run.config} failed={point.failed_components} compact/>
    <div className="panel replay-events"><div className="chart-heading"><h3>Failure & repair sequence</h3><span className="subtle">Select any row to inspect that state</span></div><div className="table-scroll"><table><thead><tr><th>Hour</th><th>Event</th><th>Component</th><th>IT served</th><th>Service</th></tr></thead><tbody>{trace.map((p,i)=><tr key={i} className={i===index?'selected-event':''}><td><button className="text-button mono" aria-label={`Replay event ${i+1}`} onClick={()=>select(i)}>{number(p.time_hours,3)}</button></td><td>{p.action}<small className="table-sub">{p.cause}</small></td><td className="mono">{p.component||'—'}</td><td>{number(p.served_it_kw)} kW</td><td><span className={`badge ${p.service_maintained?'success':'danger'}`}>{p.service_maintained?'Maintained':'Interrupted'}</span></td></tr>)}</tbody></table></div></div>
  </section>
}


function ScenarioSummary({run,result:r}: {run:Run;result:Result}) {
  const m=r.maintenance
  return <>
    {run.config.simulation.dependent_failures&&<div className="inline-note"><Info size={15}/><span>Shared-surge mode: {run.config.simulation.common_cause_events_per_year} opportunities/year × {number(run.config.simulation.common_cause_probability*100,1)}% damage probability, {run.config.simulation.common_cause_duration_hours} h repair; scope {run.config.simulation.common_cause_scope}. {number(r.scenario_events?.COMMON_CAUSE??0)} affected-unit cause starts (not unique surge events). Adds hazard; not a fixed-marginal correlation experiment.</span></div>}
    {m&&<section className="panel diagnostic-panel"><div className="chart-heading"><div><h3>{r.redundancy} · Maintenance-window evidence</h3><p>{m.component} offline for {m.window_hours} hours. {m.forced_fault?'Conditional forced-fault stress test—not an annual reliability forecast.':'One scheduled window per full trial; natural failures may overlap.'}</p></div></div><div className="diagnostic-metrics"><div><span>Maintenance alone · deterministic</span><strong>{m.maintenance_only_maintained?'Service maintained':'Service interrupted'}</strong><small>Healthy facility with only the scheduled unit offline</small></div><div><span>Monte Carlo downtime inside window</span><strong>{number(m.mean_window_downtime_minutes,3)} min</strong><small>{number(m.window_outage_trials)} / {number(r.trials_run)} trials lost service; exact risk CI {m.window_outage_probability_ci95.map(v=>number(v*100,3)).join('–')}%</small></div></div><p>Concurrent maintenance and tolerance of an additional fault are distinct properties. This limited capacity test does not establish Tier III/IV certification.</p></section>}
    {r.budget&&<details className="panel diagnostic-panel"><summary className="chart-heading">{r.redundancy} · Planning budget breakdown · {inr(r.budget.total_inr)}</summary><p>{r.budget.basis} Representative IT nodes are not a procurement inventory.</p><div className="table-scroll"><table><thead><tr><th>Type</th><th>Count</th><th>Assumed unit price</th><th>Subtotal</th></tr></thead><tbody>{r.budget.breakdown.map(b=><tr key={b.kind}><td>{b.kind}</td><td>{b.units}</td><td>{inr(b.unit_inr)}</td><td>{inr(b.subtotal_inr)}</td></tr>)}</tbody></table></div></details>}
  </>
}

function DiagnosticResults({run}: {run:Run}) {
  const d=run.diagnostics
  if(!d)return null
  const chart=d.sensitivity.map(r=>({...r,low_delta:r.low.delta_minutes,high_delta:r.high.delta_minutes}))
  const x=d.dependency_effect
  return <section className="panel diagnostic-panel" aria-label="Sensitivity diagnostics"><div className="chart-heading"><div><h3>Sensitivity / tornado chart</h3><p>Actual rate perturbations, not raw failure counts · {number(d.trials)} paired trials per rerun</p></div><span className="small-tag">Selected design: {run.config.power.redundancy} power / {run.config.cooling.redundancy} cooling / {run.config.it?.enabled?run.config.it.redundancy:'no'} IT</span></div>
    <p>{d.basis} This is a separate diagnostic baseline, not the full-sample comparison above. Confidence intervals measure Monte Carlo uncertainty only; rate provenance remains uncertain.</p>
    <div className="chart-legend"><span><i style={{background:'#23947d'}}/>Rate −50%</span><span><i style={{background:'#ec7848'}}/>Rate +50%</span></div>
    <div className="tornado-chart"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={chart} margin={{top:8,right:28,left:5,bottom:18}}><CartesianGrid horizontal={false} strokeDasharray="3 4"/><XAxis type="number" tick={{fontSize:10}} label={{value:'Change in downtime (minutes / year)',position:'bottom',fontSize:10}}/><YAxis dataKey="label" type="category" width={130} tick={{fontSize:10}}/><ReferenceLine x={0} stroke="#687b8d"/><Tooltip contentStyle={tipStyle} formatter={v=>`${number(Number(v),4)} min/year`}/><Bar dataKey="low_delta" name="Rate −50%" fill="#23947d" isAnimationActive={false}/><Bar dataKey="high_delta" name="Rate +50%" fill="#ec7848" isAnimationActive={false}/></BarChart></ResponsiveContainer></div>
    <div className="table-scroll"><table><thead><tr><th>Component rate</th><th>−50% Δ min/year · 95% CI</th><th>+50% Δ min/year · 95% CI</th><th>Evidence</th></tr></thead><tbody>{d.sensitivity.map(r=><tr key={r.kind}><td>{r.label}</td>{[r.low,r.high].map((v,i)=><td key={i}>{number(v.delta_minutes,4)}<small className="table-sub">[{v.ci95.map(n=>number(n,4)).join(', ')}]</small></td>)}<td>{r.low.evidence_limited||r.high.evidence_limited?'Sparse paired evidence':r.low.ci95[0]<=0&&r.low.ci95[1]>=0&&r.high.ci95[0]<=0&&r.high.ci95[1]>=0?'Effect unresolved':'Sample-based effect'}</td></tr>)}</tbody></table></div>
    <div className="chart-heading"><h3>Independent vs. shared-surge assumptions</h3></div><div className="diagnostic-metrics"><div><span>Independent baseline</span><strong>{number(d.baseline_downtime_minutes,3)} min/year</strong><small>No maintenance · same diagnostic sample</small></div><div><span>Dependent (additional common-cause hazard)</span><strong>{number(d.dependent_downtime_minutes,3)} min/year</strong><small>Scope {run.config.simulation.common_cause_scope}; {run.config.simulation.common_cause_events_per_year} opportunities/year × {number(run.config.simulation.common_cause_probability*100,1)}% probability; {run.config.simulation.common_cause_duration_hours} h repair</small></div></div>
    <p>Paired increase {number(x.delta_minutes,4)} min/year; approx. 95% CI [{x.ci95.map(v=>number(v,4)).join(', ')}]. {x.evidence_limited?'Too few nonzero paired differences to draw a strong conclusion.':'Sample-based estimate, not field validation.'} Motivation: <a href="https://arxiv.org/abs/2402.18187" target="_blank" rel="noreferrer">M-out-of-N dependent components (2024)</a>. The paper does not validate these numerical inputs.</p>
    {d.generator_audit&&<><div className="chart-heading"><h3>Generator source consistency check</h3></div><p>Changing from {run.config.simulation.generator_rate_basis} to {d.generator_audit.alternative_basis}: {number(d.generator_audit.delta_minutes,4)} min/year change; approx. 95% CI [{d.generator_audit.ci95.map(v=>number(v,4)).join(', ')}]. {d.generator_audit.evidence_limited?'Sparse paired evidence.':''} Printed 0.58/year versus 115/266 = 0.432330827/year. Neither is independently verified.</p></>}
  </section>
}
