import { useState } from 'react'
import { AreaChart, Area, BarChart, Bar, Cell, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, ReferenceLine, LabelList } from 'recharts'
import { Activity, ArrowDownRight, ArrowRight, Check, CheckCircle2, Clock3, Download, Info, ShieldCheck, TriangleAlert, TrendingUp, Zap } from 'lucide-react'
import { availability, number, type Result, type Run } from './types'
import { exportRun } from './exports'
const COLORS = ['#8191aa', '#ec7848', '#23947d']
const tipStyle = {background:'#fff',border:'1px solid #e5e8ef',borderRadius:9,fontSize:12,boxShadow:'0 6px 24px #17233212'}
export function Metrics({result}: {result: Result}) {
  return <div className="metrics-grid">
    <div className="metric panel"><div className="metric-label">Estimated availability<ShieldCheck size={16}/></div><strong>{availability(result.availability_percent)}<span>%</span></strong><div className={result.meets_sla?'metric-note good':'metric-note bad'}>{result.meets_sla?<TrendingUp size={13}/>:<TriangleAlert size={13}/>} {result.meets_sla?'Above':'Below'} SLA benchmark</div></div>
    <div className="metric panel"><div className="metric-label">Annual downtime<Clock3 size={16}/></div><strong>{number(result.expected_annual_downtime_minutes,2)}<span>min</span></strong><div className="metric-note">Expected per simulated year</div></div>
    <div className="metric panel"><div className="metric-label">SLA breach rate<Activity size={16}/></div><strong>{number(result.sla_breach_rate_percent,2)}<span>%</span></strong><div className="metric-note">{number(result.sla_breaches)} of {number(result.trials_run)} trials</div></div>
    <div className="metric panel"><div className="metric-label">Infrastructure index<Zap size={16}/></div><strong>{number(result.infra_cost_index,2)}<span>×</span></strong><div className="metric-note">Relative to N · unit-count basis</div></div>
  </div>
}
export function ResultsDashboard({run, onCompare}: {run: Run; onCompare: ()=>void}) {
  const [tab,setTab] = useState('overview')
  const r = run.results[0]
  const [eventFilter,setEventFilter] = useState('all')
  const lower = Math.min(r.sla_target_percent,...r.convergence.map(x=>x.availability))
  const domain = [Math.floor((lower-.0005)*1000)/1000,100]
  const events = r.sample_events.filter(e=>eventFilter==='all'||!e.service_maintained)
  return <>
    <div className="results-heading"><div><h3>Simulation results</h3><span className="badge success"><Check size={11}/>Completed</span></div><span className="subtle">{number(r.trials_run)} trials · {run.duration_seconds.toFixed(2)}s runtime</span></div>
    <Metrics result={r}/>
    <div className="results-tabs"><div role="tablist" aria-label="Simulation result views">{[['overview','Overview'],['distribution','Trial distribution'],['events','Event samples']].map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><button className="text-button" onClick={()=>exportRun(run,'trials')}><Download size={13}/>Trial data</button></div>
    {tab==='overview' && <div className="charts-grid"><section className="panel convergence-panel"><div className="chart-heading"><div><h3>Availability convergence</h3><p>Cumulative estimate across simulation trials</p></div><span className="small-tag">{r.redundancy}</span></div><div className="chart-legend"><span><i style={{background:'#ea7849'}}/>Estimated availability</span><span><i className="dashed"/>SLA benchmark</span></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><AreaChart data={r.convergence} margin={{top:10,right:16,left:0,bottom:5}}><defs><linearGradient id="convergence-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ef8055" stopOpacity={.18}/><stop offset="100%" stopColor="#ef8055" stopOpacity={.01}/></linearGradient></defs><CartesianGrid strokeDasharray="3 4" vertical={false} stroke="#edf0f3"/><XAxis dataKey="trials" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8c94a2'}} tickFormatter={v=>v>=1000?`${v/1000}k`:v} minTickGap={25}/><YAxis domain={domain} axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#8c94a2'}} tickFormatter={v=>`${v.toFixed(3)}%`} width={76} tickCount={4}/><Tooltip contentStyle={tipStyle} formatter={v=>[`${Number(v).toFixed(6)}%`,'Availability']} labelFormatter={v=>`${number(Number(v))} trials`}/><ReferenceLine y={r.sla_target_percent} stroke="#a2adba" strokeDasharray="5 4"/><Area isAnimationActive={false} type="monotone" dataKey="availability" stroke="#ed794b" strokeWidth={2} fill="url(#convergence-fill)"/></AreaChart></ResponsiveContainer></div><div className="chart-footer">Approx. 95% mean CI <span>{r.availability_ci95.map(x=>x.toFixed(5)).join(' – ')}%</span></div></section>
    <section className="panel breakdown-panel"><div className="chart-heading"><div><h3>Failure breakdown</h3><p>Sampled component failure events</p></div><span className="icon-muted"><Activity size={16}/></span></div><div className="breakdown-list">{[...r.failure_breakdown].sort((a,b)=>b.failures-a.failures).map((b,i)=><div key={b.kind}><div><span><i style={{background:['#ed7848','#7a91b7','#a7b7cc','#60aa9b','#b4bccc'][i]}}/>{b.component}</span><strong>{number(b.failures)}</strong></div><div className="breakdown-track"><i style={{width:`${Math.max(0,b.failures/Math.max(1,r.total_failure_events)*100)}%`,background:['#ed7848','#7a91b7','#a7b7cc','#60aa9b','#b4bccc'][i]}}/></div></div>)}</div><div className="breakdown-total"><span>Total injected events</span><strong>{number(r.total_failure_events)}</strong></div></section></div>}
    {tab==='distribution' && <section className="panel"><div className="chart-heading"><div><h3>Annualized downtime distribution</h3><p>How often did the facility experience an interruption?</p></div><span className="small-tag">{number(r.outage_trials)} outage trials</span></div><div className="distribution-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={r.histogram} margin={{top:25,right:25,bottom:10,left:10}}><CartesianGrid vertical={false} strokeDasharray="3 4"/><XAxis dataKey="range" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={tipStyle}/><Bar dataKey="trials" fill="#ec7848" radius={[5,5,0,0]} maxBarSize={70}>{r.histogram.map((_,i)=><Cell key={i} fill={i===0?'#38a38b':'#ed8055'}/>)}<LabelList dataKey="trials" position="top" style={{fontSize:11,fill:'#657081'}}/></Bar></BarChart></ResponsiveContainer></div><div className="chart-footer">95th percentile annual downtime <span>{number(r.p95_annual_downtime_minutes,2)} min</span></div></section>}
    {tab==='events' && <section className="panel"><div className="chart-heading"><div><h3>Failure event samples</h3><p>First 60 events, ordered by trial—not a representative event sample.</p></div><select aria-label="Filter failure events" className="compact-select" value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option value="all">All events</option><option value="impact">Service interrupted</option></select></div><div className="table-scroll events-table"><table><thead><tr><th>Trial</th><th>Component</th><th>At hour</th><th>Repair time</th><th>Capacity</th><th>Service</th></tr></thead><tbody>{events.slice(0,30).map((e,i)=><tr key={i}><td className="mono">#{e.trial_id}</td><td className="mono">{e.component}</td><td>{number(e.time_hours,2)}</td><td>{e.duration_hours} h</td><td>{number(e.surviving_capacity_kw)} kW</td><td><span className={`badge ${e.service_maintained?'success':'danger'}`}>{e.service_maintained?'Maintained':'Interrupted'}</span></td></tr>)}</tbody></table>{!events.length&&<div className="empty-inline">No interruptions in the captured event samples. Full aggregate results are shown above.</div>}</div></section>}
    <div className="result-insight"><div className="insight-icon"><ShieldCheck size={20}/></div><div><strong>{r.meets_sla?'Your design meets the selected mean-availability benchmark.':'This design falls below the selected availability benchmark.'}</strong><p>{number(r.overlap_trials)} trials contained overlapping failures. {r.outage_trials===0?`No outages observed; 95% upper bound on trial outage probability is ${(r.outage_probability_ci95[1]*100).toFixed(3)}%.`:`${number(r.outage_trials)} trials lost IT service; uptime is not guaranteed by the mean.`}</p></div><button onClick={onCompare}>Compare designs<ArrowRight size={15}/></button></div>
    <div className="inline-note"><Info size={14}/><span>Mixed-source research demo · {run.config.simulation.operating_mode} scenario · {run.config.simulation.stress_multiplier}× hazard rate. Estimates are model-dependent, not Tier certification.</span></div>
  </>
}
export function Comparison({run}: {run: Run}) {
  const rs = run.results
  const min = Math.min(...rs.map(r=>r.availability_percent))
  const nDown = rs[0].expected_annual_downtime_minutes
  const best = [...rs].filter(r=>r.meets_sla).sort((a,b)=>a.infra_cost_index-b.infra_cost_index)[0]
  return <div className="comparison-results"><div className="comparison-summary"><div><span className="eyebrow">CONTROLLED COMPARATIVE STUDY</span><h2>Same load. Different resilience.</h2><p>{number(run.config.it_load_kw)} kW · {number(run.config.simulation.num_trials)} trials per design · seed {run.config.simulation.seed}</p></div><span className="badge success"><CheckCircle2 size={13}/>Experiment complete</span></div>
    <div className="architecture-cards">{rs.map((r,i)=><article className={`panel architecture-card ${r.redundancy===best?.redundancy?'recommended':''}`} key={r.redundancy}><div className="architecture-top"><span className="architecture-symbol" style={{color:COLORS[i],background:`${COLORS[i]}13`}}>{r.redundancy}</span>{r.redundancy===best?.redundancy?<span className="badge orange">Lowest-cost SLA fit</span>:<span className="subtle">{['Baseline','One spare / group','Independent A/B paths'][i]}</span>}</div><strong>{availability(r.availability_percent)}<small>%</small></strong><span className="subtle">Estimated availability</span><div className="architecture-stats"><div><span>Annual downtime</span><b>{number(r.expected_annual_downtime_minutes,2)} min</b></div><div><span>Infrastructure cost index</span><b>{number(r.infra_cost_index,2)}×</b></div><div><span>Installed components</span><b>{r.component_count}</b></div></div><div className={`architecture-status ${r.meets_sla?'good':'bad'}`}>{r.meets_sla?<CheckCircle2 size={14}/>:<TriangleAlert size={14}/>} {r.meets_sla?'Meets mean SLA benchmark':'Below mean SLA benchmark'}</div></article>)}</div>
    <div className="charts-grid equal"><section className="panel"><div className="chart-heading"><div><h3>Availability by architecture</h3><p>Percent uptime · zoomed vertical axis</p></div></div><div className="comparison-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rs} margin={{left:10,right:20,top:25,bottom:5}}><CartesianGrid vertical={false} strokeDasharray="3 4" stroke="#e9edf2"/><XAxis dataKey="redundancy" tickLine={false} axisLine={false} tick={{fontSize:12}}/><YAxis domain={[Math.max(0,Math.floor((min-.01)*100)/100),100]} tickFormatter={v=>`${v.toFixed(2)}%`} tick={{fontSize:10}} width={65} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[`${Number(v).toFixed(6)}%`,'Availability']} contentStyle={tipStyle}/><ReferenceLine y={rs[0].sla_target_percent} stroke="#8892a1" strokeDasharray="4 4"/><Bar dataKey="availability_percent" radius={[5,5,0,0]} maxBarSize={65}>{rs.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Bar></BarChart></ResponsiveContainer></div></section><section className="panel"><div className="chart-heading"><div><h3>The downtime trade-off</h3><p>Expected minutes of downtime per year</p></div></div><div className="comparison-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rs} margin={{left:10,right:30,top:25,bottom:5}}><CartesianGrid vertical={false} strokeDasharray="3 4" stroke="#e9edf2"/><XAxis dataKey="redundancy" tickLine={false} axisLine={false} tick={{fontSize:12}}/><YAxis tick={{fontSize:10}} width={45} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[`${number(Number(v),3)} min`,'Annual downtime']} contentStyle={tipStyle}/><Bar dataKey="expected_annual_downtime_minutes" radius={[5,5,0,0]} maxBarSize={65}>{rs.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Bar></BarChart></ResponsiveContainer></div></section></div>
    <section className="panel"><div className="chart-heading"><div><h3>Experiment results</h3><p>Identical load, component ratings, horizon, and hazard assumptions.</p></div><button className="text-button" onClick={()=>exportRun(run,'csv')}><Download size={14}/>Export CSV</button></div><div className="table-scroll"><table><thead><tr><th>Architecture</th><th>Availability (95% mean CI)</th><th>Downtime / year</th><th>SLA breaches</th><th>Cost index</th><th>Overlapping trials</th></tr></thead><tbody>{rs.map(r=><tr key={r.redundancy}><td><b>{r.redundancy}</b></td><td>{availability(r.availability_percent)}%<small className="table-sub">{r.availability_ci95.map(x=>x.toFixed(5)).join(' – ')}%</small></td><td>{number(r.expected_annual_downtime_minutes,3)} min</td><td>{number(r.sla_breach_rate_percent,2)}%<small className="table-sub">{number(r.sla_breaches)} trials</small></td><td>{number(r.infra_cost_index,2)}×</td><td>{number(r.overlap_trials)}</td></tr>)}</tbody></table></div></section>
    <div className="result-insight"><div className="insight-icon"><ArrowDownRight size={21}/></div><div><strong>{best?`${best.redundancy} is the lowest unit-count design meeting the mean SLA benchmark in this run.`:'None of the tested designs meets the mean SLA benchmark.'}</strong><p>{nDown>0?`N+1 changes expected downtime by ${number((1-rs[1].expected_annual_downtime_minutes/nDown)*100,2)}% relative to N. `:''}Overhead uses equal unit weights, not real procurement costs. Rare-event rankings can vary by seed.</p></div></div><div className="inline-note"><Info size={15}/><span>Zero observed downtime is not infinite reliability. This {run.config.simulation.stress_multiplier}× {run.config.simulation.operating_mode} experiment uses illustrative PDU/cooling values. Download JSON for complete assumptions and data provenance.</span></div>
  </div>
}
