import { useState } from 'react'
import { ArrowUpRight, BookOpen, CheckCircle2, Download, ExternalLink, FileCode2, FlaskConical, Info, Search, ShieldCheck, TriangleAlert } from 'lucide-react'
import { download } from './exports'
import { number, type Rate } from './types'
export function References({rates}: {rates: Rate[]}) {
  const [search,setSearch] = useState('')
  const [filter,setFilter] = useState('all')
  const shown = rates.filter(r=>r.label.toLowerCase().includes(search.toLowerCase()) && (filter==='all'||r.status===filter))
  return <div className="reference-page"><div className="reference-hero"><div className="reference-hero-icon"><BookOpen size={30}/></div><div><span className="eyebrow">TRANSPARENT BY DESIGN</span><h2>Every assumption has a source.</h2><p>Understand the data behind your experiment. No invented IEEE citations. No hidden model assumptions.</p></div></div><div className="reference-stats"><div className="panel"><FileCode2 size={21}/><div><b>{rates.length}</b><span>Modelled failure types</span></div></div><div className="panel"><CheckCircle2 size={21} className="text-green"/><div><b>{rates.filter(r=>r.status==='secondary-source').length}</b><span>Secondary-source records</span></div></div><div className="panel"><TriangleAlert size={21} className="text-orange"/><div><b>{rates.filter(r=>r.status==='illustrative').length}</b><span>Explicit demo assumptions</span></div></div></div>
    <div className="data-warning"><Info size={18}/><div><strong>Research demo, not a verified IEEE dataset.</strong><p>UPS, generator and ATS values are transcribed from Wiboonrat (2020), Table 2, which cites IEEE Std 493-2007. PDU and CRAC values remain illustrative README midpoints: the full Table 2 has no PDU/CRAC entries. All five IT rates are explicitly educational assumptions, not IEEE data. Generator audit: printed 0.58/year versus 115/266 = 0.432330827/year; the app can compare both. Validate equipment classes and replace assumptions before submitting paper results.</p></div></div>
    <section className="panel"><div className="reference-toolbar"><div className="search-input"><Search size={16}/><input aria-label="Search component references" placeholder="Search components…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter reference sources" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All sources</option><option value="secondary-source">Secondary source</option><option value="illustrative">Illustrative assumptions</option></select><button className="button" onClick={()=>download(JSON.stringify(rates,null,2),'DC_Resilience_failure_rates.json','application/json')}><Download size={14}/>Dataset</button></div><div className="table-scroll"><table className="references-table"><thead><tr><th>Component</th><th>Failure rate / year</th><th>MTTR</th><th>Data provenance</th></tr></thead><tbody>{shown.map(r=><tr key={r.component}><td><b>{r.label}</b><small className="table-sub mono">{r.component}</small></td><td className="mono">{r.failure_rate_per_year}</td><td className="mono">{r.mttr_hours} hours</td><td><span className={`badge ${r.status==='illustrative'?'warning':'success'}`}>{r.status==='illustrative'?'Illustrative · unverified':'Cited secondary source'}</span><p>{r.source}</p><small>{r.notes}</small>{r.source_url&&<a href={r.source_url} target="_blank" rel="noreferrer">View source · Table 2 <ExternalLink size={12}/></a>}</td></tr>)}</tbody></table>{!shown.length&&<div className="empty-inline">No components match this search.</div>}</div></section>
    <div className="source-cards"><a className="panel" href="https://www.intechopen.com/chapters/73642" target="_blank" rel="noreferrer"><BookOpen size={22}/><h3>Secondary dataset reference</h3><p>M. Wiboonrat (2020). Condition-Based Maintenance for Data Center Operations Management. DOI: 10.5772/intechopen.93945.</p><span>Read open-access chapter <ArrowUpRight size={15}/></span></a><a className="panel" href="https://standards.ieee.org/ieee/493/3402/" target="_blank" rel="noreferrer"><ShieldCheck size={22}/><h3>IEEE Std 493-2007</h3><p>Recommended Practice for the Design of Reliable Industrial and Commercial Power Systems. The underlying Gold Book standard.</p><span>View standard details <ArrowUpRight size={15}/></span></a></div>
  </div>
}
export function Methodology() {
  return <div className="methodology-page"><div className="method-hero"><div><span className="eyebrow">THE SCIENCE BEHIND THE SIMULATION</span><h2>Reliability, not guesswork.</h2><p>A reproducible, continuous-time Monte Carlo model for a controlled study of data centre redundancy.</p></div><FlaskConical size={70} strokeWidth={1}/></div><div className="method-grid">{[
    ['01','Configure a fair experiment','Hold IT load, per-unit ratings, simulation horizon, operating scenario and seed constant. Only the redundancy architecture changes. Required units = ceil(load / unit capacity).'],
    ['02','Sample hardware and software failures','Each component has exponentially distributed operating lifetimes; OS crashes act on the same host as server hardware faults, with independent cause clocks. Fixed 256-trial batches bound memory; stable source/bank/unit/batch seeds preserve trial prefixes when more trials are requested. Repairs use a constant duration equal to the recorded MTTR.'],
    ['03','Sweep failures and repairs','Events are sorted chronologically. The engine tracks all currently failed units, calculates surviving capacity, and integrates outage intervals exactly—overlapping downtime is never double counted.'],
    ['04','Measure and compare','Aggregate trial availability, annualized downtime, SLA breaches, lost-capacity energy and equal-weight infrastructure cost. Export every trial and the full configuration to reproduce the study.']
  ].map(([n,title,text])=><article className="panel" key={n}><span className="step-number">{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div>
    <section className="panel formula-panel"><div className="chart-heading"><h3>Core equations</h3><span className="small-tag">Dimensionally consistent</span></div><div className="formula-grid"><div><span>Operating time to failure (hours)</span><code>TTF ~ Exp(scale = 8,760 / λyear)</code></div><div><span>Trial availability</span><code>A = 100 × (1 − downtime / horizon)</code></div><div><span>Expected annual downtime (minutes)</span><code>D = (1 − A / 100) × 525,600</code></div><div><span>Single-component check (hours / year)</span><code>D ≈ λyear × MTTRhours</code></div></div><div className="inline-note"><Info size={15}/><span>When λ is already failures/year, do not multiply λ × MTTR by 8,760 again. The original README’s validation formula contains this units error; the implementation and tests use the corrected equation.</span></div></section>
    <div className="method-columns"><section className="panel"><h3>What each architecture means</h3><dl><dt>N · minimum serving set</dt><dd>Exactly the number of units needed to cover load, rounded up. A unit failure can remove required capacity.</dd><dt>N+1 · one spare per group</dt><dd>The serving set plus one extra unit in each UPS, generator, PDU, ATS, cooling and enabled IT group.</dd><dt>2N · independent full paths</dt><dd>Two complete power, cooling and IT trains. IT includes representative server nodes, OS/hypervisor, storage, network and application availability; IT capacity means equal workload shares, not server electrical draw. No cross-ties: a UPS failure in path A and a PDU failure in path B may interrupt service even when pooled capacity appears sufficient.</dd></dl></section><section className="panel"><h3>Confidence, not certainty</h3><p>Availability intervals normally use a sample-mean normal approximation. With zero outages, a conservative bound is instead derived from exact trial-outage risk, avoiding a misleading [100%, 100%] interval. Fewer than 30 outage trials triggers a heuristic caution flag, not a formal adequacy test.</p><p>For the probabilities of a trial having any outage or breaching its SLA benchmark, the engine also computes an exact 95% Clopper–Pearson interval. Zero observed outages therefore still has a non-zero upper risk bound.</p><p>Paired comparison intervals use the trial-by-trial downtime difference between architectures. Trial replay selects the maximum-downtime trial, not a typical year. Multi-year SLA breaches compare the full-horizon average, not each year separately. 10,000 trials may not resolve extremely rare failures. Try another seed, longer horizons or clearly labelled stress experiments. Stress results do not represent baseline operation.</p></section></div>
    <section className="panel assumptions"><h3>Modelling boundaries</h3><div>{['Islanded mode assumes continuous generator operation. Utility mode assumes a perfectly available grid; generator failures cannot interrupt IT service.','Independent random failures can overlap. Optional common-cause surges are a thinned Poisson process affecting UPS/generator units in bank A or across the site. Defaults (1 opportunity/year, 10% damage chance, 4-hour repair) are assumptions, not values from arXiv:2402.18187. This adds a hazard, not a fixed-marginal correlation coefficient. General cascading propagation is not modelled.','Single-failure mode intentionally suppresses overlapping starts. It is a controlled baseline, not an independent-failure stochastic model.','Perfect repair and instantaneous failover are assumed. Scheduled maintenance has explicit start/end events; optional forced same-group faults are conditional stress, not an annual field forecast. Tier III concurrent maintenance does not itself require tolerating an extra fault. Battery autonomy, per-demand generator start failures, fuel depletion and thermal inertia remain unmodelled.','Tier I–IV percentages are historical SLA benchmarks, not the Uptime Institute’s certification criteria. Availability alone cannot establish a Tier.','The legacy index is equal-weight component count. New editable INR planning budgets use per-kW facility inputs and per-node IT inputs. These are educational assumptions, not sourced market quotes; exclude tax, installation, software licensing and OPEX.'].map((t,i)=><p key={i}><Info size={15}/>{t}</p>)}</div></section>
    <section className="panel assumptions"><h3>Research caveats and diagnostic interpretation</h3><p>The full Wiboonrat Table 2 does not verify PDU or CRAC rates. The generator record conflicts internally: 115 failures / 266 unit-years ≈ 0.43233/year; the printed rate is 0.58/year, consistent with its printed MTBF of 15,033.8 h. Neither should support a headline field-availability claim without validation. The diagnostic panel reruns the alternative interpretation.</p><p>Sensitivity uses actual one-at-a-time ±50% rate reruns with at most 1,000 paired trials on the selected architecture, independent overlapping mode, no maintenance, same stress and seed. It shows delta downtime and approximate confidence intervals. A failure-count ranking is not a sensitivity analysis. Sparse differences are explicitly flagged.</p><p>The IT extension is an availability abstraction: representative compute nodes plus network, storage and application replicas. No packet-level topology, disk durability, quorum, VM scheduling, workload latency, attack simulation or full operating-system implementation is claimed. Source rates, topology and settings are exported for reproducibility.</p><p>The workload guardrail budgets the largest 2N design and OS streams; the form blocks oversized jobs and offers a safe trial count. Two CPU jobs may run simultaneously; HTTP 429 includes Retry-After. No automatic resubmission duplicates a run.</p></section>
    <footer className="research-credit"><span>SRM INSTITUTE OF SCIENCE AND TECHNOLOGY</span><h3>Built for a better understanding of resilience.</h3><p>Romit Deokar · RA2411003010615 &nbsp; / &nbsp; Shourya Saran · RA2411003010628</p><p>21CSE745P — Foundations of Data Centre Infrastructure and Management</p><small>{number(100)}% open-source stack. No paid APIs. No physical sensors. No AI claims.</small></footer>
  </div>
}
