import { Activity, ArrowRight, BatteryCharging, Check, CircuitBoard, Fuel, Info, LoaderCircle, RotateCcw, Server, Snowflake, Zap, X } from 'lucide-react'
import { number, type Config, type FacilityState, type Group } from './types'
const icons: Record<string, typeof Zap> = {UPS_MODULE: BatteryCharging, GENERATOR: Fuel, PDU: CircuitBoard, ATS: Zap, CRAC: Snowflake, SERVER: Server, NETWORK: CircuitBoard, STORAGE: Server, APPLICATION: Activity}
const labels: Record<string, string> = {UPS_MODULE:'UPS modules',GENERATOR:'Generators',PDU:'Power distribution',ATS:'Transfer switches',CRAC:'Cooling units',SERVER:'Server hardware + OS',NETWORK:'Network service',STORAGE:'Storage service',APPLICATION:'Application service'}
export function FacilityDiagram({state, config, failed = [], onToggle, compact = false, disabled=false, unavailable=false}: {state: FacilityState | null; config: Config; failed?: string[]; onToggle?: (id: string)=>void; compact?: boolean; disabled?: boolean; unavailable?: boolean}) {
  const count = state?.groups.reduce((a,g)=>a+g.components.length,0) || 0
  return <section className={`facility-diagram ${compact?'compact':''}`}>
    <div className="diagram-heading"><div><span className="eyebrow">FACILITY TOPOLOGY</span><h3>{config.facility_name || 'Untitled facility'} <span className="dark-chip">Tier {config.tier_target}</span></h3></div><span className={`live-status ${state && !state.service_maintained?'failed':''}`}><i/>{state ? state.service_maintained?'Service maintained':'Capacity degraded':unavailable?'Invalid configuration':'Loading topology'}</span></div>
    <div className="diagram-content">
      <div className="source-node"><div className="source-icon"><Zap size={21}/></div><span>{config.simulation.operating_mode === 'islanded' ? 'Islanded power' : 'Utility supply'}</span><small>{config.simulation.operating_mode === 'islanded' ? 'Generator-backed scenario' : 'Ideal grid assumption'}</small></div>
      <div className="connector-line"><span/></div>
      <div className="equipment-groups">{state ? state.groups.filter(g=>g.kind!=='ATS' || !compact).map(group=><Equipment key={group.kind} group={group} failed={failed} onToggle={onToggle} compact={compact} disabled={disabled}/>) : <div className="diagram-loading">{!unavailable&&<LoaderCircle className="spin"/>} {unavailable?'Fix the configuration to preview equipment':'Preparing facility topology'}</div>}</div>
      <div className={`connector-line output ${state && !state.service_maintained?'broken':''}`}><span/></div>
      <div className={`load-node ${state && !state.service_maintained?'degraded':''}`}><Server size={25}/><div><strong>{number(config.it_load_kw)} <small>kW</small></strong><span>Critical IT load</span></div><div className="load-status">{state?.service_maintained?<Check size={15}/>:<Activity size={15}/>}</div></div>
    </div>
    <div className="diagram-footer"><span><i className="legend-dot green"/>Healthy{onToggle && <><i className="legend-dot red"/>Failed</>}<i className="legend-dot outlined"/>{count} components{compact?' · including ATS':''}</span><span>{onToggle?'Click a unit to inject / repair':`${config.power.redundancy} power · ${config.cooling.redundancy} cooling`}{!onToggle && <ArrowRight size={13}/>}</span></div>
  </section>
}
function Equipment({group, failed, onToggle, compact, disabled}: {group: Group; failed: string[]; onToggle?: (id: string)=>void; compact: boolean; disabled: boolean}) {
  const Icon = icons[group.kind] || Zap
  const broken = group.components.some(c=>failed.includes(c.id))
  return <div className={`equipment ${broken?'has-failure':''}`}><div className="equipment-title"><Icon size={15}/><span>{labels[group.kind] || group.kind}</span><b>{group.redundancy}</b></div><div className="equipment-units">{group.components.slice(0,compact?8:80).map(c=><button key={c.id} type="button" disabled={!onToggle || disabled} aria-label={`${failed.includes(c.id)?'Repair':'Fail'} ${c.id}`} title={`${c.id} · ${number(c.capacity_kw)} kW · click to ${failed.includes(c.id)?'repair':'fail'}`} onClick={()=>onToggle?.(c.id)} className={`unit ${failed.includes(c.id)?'unit-failed':''}`}><span className="unit-light"/>{compact?<div className="unit-slats"><i/><i/><i/></div>:<><Icon size={16}/><span>{c.id}</span></>}{failed.includes(c.id)&&<X className="unit-x" size={10}/>}</button>)}{compact && group.components.length>8 && <span className="unit-overflow">+{group.components.length-8}</span>}</div><span className="equipment-caption">{group.components.length} units <span>× {number(group.capacity_kw_each,1)} {group.subsystem==='it'?'workload-kW':'kW'}</span></span></div>
}
export function FailureLab({config, state, failed, busy, onToggle, onReset, onScenario, logs, duration, onDuration, unavailable}: {duration: number; onDuration: (hours:number)=>void; unavailable: boolean; config: Config; state: FacilityState|null; failed: string[]; busy: boolean; onToggle: (id: string)=>void; onReset: ()=>void; onScenario: (s: string)=>void; logs: {time: string; text: string; healthy: boolean}[]}) {
  return <div className="lab-content">
    <div className="lab-prompt"><div className="prompt-icon"><Zap size={20}/></div><div><h3>Break a component. Test your design.</h3><p>Click any unit to take it offline. Watch redundancy protect your IT load—or reach its limit.</p></div><button className="button" onClick={onReset} disabled={busy || !failed.length}><RotateCcw size={15}/>Restore all</button></div>
    <div className="scenario-bar"><span>QUICK SCENARIOS</span><button disabled={busy} onClick={()=>onScenario('single')}>Single UPS failure</button><button disabled={busy} onClick={()=>onScenario('double')}>Dual UPS failure</button><button disabled={busy} onClick={()=>onScenario('path')}>Power path A outage</button><button disabled={busy||config.power.redundancy!=='2N'} title="Requires 2N power" onClick={()=>onScenario('cross')}>Cross-path failure</button><button disabled={busy} onClick={()=>onScenario('cooling')}>Cooling capacity loss</button></div>
    {config.it.enabled&&<div className="scenario-bar"><span>IT SERVICE SCENARIOS</span>{[['server','Server hardware'],['os','OS / hypervisor crash'],['servers','Two server nodes'],['storage','All storage replicas'],['network','All network replicas'],['application','All application replicas']].map(([id,label])=><button key={id} disabled={busy} onClick={()=>onScenario(id)}>{label}</button>)}</div>}
    <div className="scenario-bar"><span>SHARED HAZARD</span><button disabled={busy} onClick={()=>onScenario('surge')}>Site-wide UPS + generator surge</button><small>Deterministic forced scenario. Use maintenance controls + Run simulation for timed maintenance.</small></div>
    <div className="lab-duration"><label htmlFor="duration">Hold failures for</label><select id="duration" disabled={busy} value={duration} onChange={e=>onDuration(Number(e.target.value))}>{[.25,1,2,4,8,24].map(h=><option key={h} value={h}>{h===.25?'15 minutes':`${h} hour${h===1?'':'s'}`}</option>)}</select><span>Hypothetical duration · scenarios replace existing failures</span></div>
    <FacilityDiagram unavailable={unavailable} state={state} config={config} failed={failed} onToggle={onToggle} disabled={busy}/>
    <div className="lab-metrics"><div className="panel"><span>Surviving capacity</span><strong>{number(state?.surviving_capacity_kw || 0)}<small> kW</small></strong><div className="capacity-meter"><i style={{width:`${Math.min(100,(state?.surviving_capacity_kw || 0)/config.it_load_kw*100)}%`,background:state?.service_maintained?'var(--green)':'var(--red)'}}/></div><small>{number(config.it_load_kw)} kW required</small></div><div className="panel"><span>IT capacity lost</span><strong className={state?.lost_capacity_kw?'text-red':''}>{number(state?.lost_capacity_kw || 0)}<small> kW</small></strong><small>{number((state?.lost_capacity_kw || 0)/config.it_load_kw*100,1)}% of required IT load</small></div><div className="panel"><span>Active failures</span><strong>{failed.length}<small> units</small></strong><small>{failed.length===0?'All components operational':'Click failed units to restore them'}</small></div><div className="panel"><span>Scenario impact</span><strong className={state?.service_maintained?'text-green':'text-red'}>{!state?'Unavailable':state.service_maintained?'Protected':'Interrupted'}</strong><small>{!state?'No valid topology':state.service_maintained?'No IT service interruption':`${number(duration*60)} min downtime if held for ${duration} h`}</small></div></div>
    {state&&<div className="capacity-summary panel"><div><span>Usable power</span><strong>{number(state.power_capacity_kw)} kW</strong></div><div><span>Usable cooling</span><strong>{number(state.cooling_capacity_kw)} kW</strong></div><div><span>Usable IT workload</span><strong>{number(state.it_capacity_kw??config.it_load_kw)} workload-kW</strong></div><div><span>Unserved energy over {duration} h</span><strong>{number(state.lost_capacity_kw*duration,2)} kWh</strong></div><p>Service is the minimum of usable power, cooling and IT workload capacity. Each 2N train must be complete. OS crashes affect their host, not an independent pool; workload-kW is not server electrical draw.</p></div>}
    <div className="panel event-console"><div className="panel-heading"><h3><Activity size={16}/> Injection event log</h3><span className="subtle">Current session</span></div><div className="console-body">{logs.length?logs.slice(0,12).map((log,i)=><div key={i}><span className="mono">{log.time}</span><span className={log.healthy?'console-ok':'console-fail'}>{log.healthy?'PROTECTED':'DEGRADED'}</span><span>{log.text}</span></div>):<div><span className="mono">READY</span><span className="console-ok">HEALTHY</span><span>Facility initialized. Select a scenario or click a component to begin.</span></div>}</div></div>
    <div className="inline-note"><Info size={15}/><span>Deterministic live injection, not a Monte Carlo forecast. Failures persist until repaired. Named scenarios force component states; OS and hardware buttons have the same host-capacity effect. The Monte Carlo engine separately samples both causes. No thermal-delay or full software stack model.</span></div>
  </div>
}
